%% Generated by lilypond-book
%% Options: [indent=0\mm,staffsize=34]
\include "lilypond-book-preamble.ly"


% ****************************************************************
% Start cut-&-pastable-section
% ****************************************************************

#(ly:set-option 'eps-box-padding 3.000000)

#(set-global-staff-size 34)

\paper {
  indent = 0\mm
}

\layout {
  
}




% ****************************************************************
% ly snippet:
% ****************************************************************
\sourcefileline 2

\key e \major
\time 4/4
r1\fermata r1\fermata r2 r4 b'8.\trill ais32 (b) e4 b8.. (b32) b4 cis4\accent cis2 (fis,4) r4 




% ****************************************************************
% end ly snippet
% ****************************************************************
